services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pki2fa_app
    ports:
      - "8080:8080"
    volumes:
      # persistent volumes
      - seed-data:/data
      - cron-output:/cron

      # mount keys read-only
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro
    environment:
      TZ: UTC
    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
